/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.watterizer.panels;

import com.watterizer.util.UsefulMethods;
import java.awt.Font;

/**
 *
 * @author 15153769
 */
public class Milagre1 extends javax.swing.JPanel {

    /**
     * Creates new form SelectConfig
     */
    public Milagre1() {
        initComponents();
//        text.setText("<html><body style=\"text-align: justify;\">    Ao configurar o terminal como Seeder, é necessário que o computador tenha uma unidade Arduino "
//                + "conectada a ele, e este Arduino também precisa de ao menos um medidor para consumir os gastos de uma fonte elétrica. Primeiramente, cheque a "
//                + "comunicação com este terminal para com o Arduino com os controles abaixo:</body></html>");
//        text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setVerifyInputWhenFocusTarget(false);

        previous.setText("Anterior");

        next.setText("Próximo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previous)
                .addGap(428, 428, 428)
                .addComponent(next)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previous)
                    .addComponent(next))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    // End of variables declaration//GEN-END:variables
}
